version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
    app:
        build:
            context: ./docker/php
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        depends_on:
            - mysql
        networks:
            - laravel
        deploy:
            resources:
                limits:
                    cpus: '0.75'
                    memory: '512M'
    web:
        image: nginx:latest
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel
volumes:
    dbdata:

networks:
    laravel:
